name: Generate Trophy

on:
  schedule:
    - cron: "0 */12 * * *"   # generate ulang setiap 12 jam
  workflow_dispatch: {}       # bisa dijalankan manual dari tab Actions
  push:
    branches:
      - main

jobs:
  trophy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: adillahaku
          output_path: trophy.svg
          theme: gruvbox
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated: trophy card"; then
            git push
          fi
